# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jm3nXRxVQ9UM2C3n07wjEqrOn9Q-_wNB
"""

import streamlit as st
import joblib
import numpy as np

model = joblib.load('Virtual.pkl')
st.title("RB-B8 Production Forcasting")

Freq = st.slider("Status-Hz[Hz]", 30, 70)
PIP = st.slider("Press-Pump Intake (Pi)[psi]", 1000 , 3500)
Tm = st.slider("Temp-Motor[degF]", 100 , 350)
Vx = st.slider("Vib-Pump X axis[G]", 0.0 ,5.0, step=0.1)
Vy = st.slider("Vib-Pump Y axis[G]", 0.0 ,5.0, step=0.1)
PDP = st.slider("Press-Pump Discharge[psi]", 1000 ,4500)
Motor_Amps = st.slider("Pwr-Motor Amps Ph B[A]", 0 ,80)

if st.button("Predict"):
    X_new = np.array([[Freq,PIP,Tm,Vx,Vy,PDP,Motor_Amps]])
    prediction = model.predict(X_new)[0]
    st.success(f"Predicted flow: {prediction:,.2f}")
